#!/usr/bin/env bash
# Install nginx web server
# Replace default page with Hello world!
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
service nginx start
