#!/usr/bin/env bash
# Sets up /redirect_me page redirection

sudo apt-get update
sudo apt-get install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html

replacing_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/mbururionge permanent;"

sudo sed -i "s/server_name _;/$replacing_string/" /etc/nginx/sites-enabled/default

sudo service nginx restart
