#!/usr/bin/env bash
# Sets up an error 404 page

sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html

replacing_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/mbururionge permanent;"

sudo sed -i "s/server_name _;/$replacing_string/" /etc/nginx/sites-enabled/default

# create an error 404 page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

replacing_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$replacing_string/" /etc/nginx/sites-enabled/default

sudo service nginx restart
