#!/usr/bin/env bash

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

FILE="/etc/nginx/sites-available/default"
REDIRECT="location /redirect_me {\n return 301 https://youtu.be/dQw4w9WgXcQ;\n}\n"
STRING=" error_page 404 /404.html;\n location = /404.html {\n root /usr/share/nginx/html;\n internal;\n}\n"
apt-get -y update
apt-get -y install nginx
echo "Hello World!" | tee /usr/share/nginx/html/index.html
echo "Ceci n'est pas une page" | tee /usr/share/nginx/html/404.html
service nginx start
if ! grep -q "location /redirect_me" "$FILE"; then
    sed -i "30i $REDIRECT" "$FILE"
fi

if ! grep -q "error_page 404 /404.html" "$FILE"; then
    sed -i "33i $STRING" "$FILE"
fi

service nginx restart
