#!/usr/bin/env bash
#Sets up load balancer
sudo apt install -y haproxy=1.5\*
file=/etc/haproxy/haproxy.cfg
sudo echo -e "frontend haproxynode
\tbind *:80
\tmode http
\tdefault_backend nodes" | sudo tee -a $file
sudo echo -e "backend nodes
\tmode http
\tbalance roundrobin
\toption fowardfor
\thttp-request set-header X-Fowarded-Port %[dst_port]
\tserver 427159-web-01 54.157.176.195:80 check
\tserver 427159-web-02 52.91.182.133:80 check" | sudo tee -a $file
sudo service haproxy restart
