#!/usr/bin/env bash
# configures a server to listening on port 80 of all servers active IPv4 IPs

#removes the default nginx configuration file
rm /etc/nginx/sites-enabled/default

#configure nginx to listen on port 80 for all active IPv4 IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

#restart nginx
sudo service nginx restart
