#!/usr/bin/env bash
# This script displays "Best School" 10 times, "Hi" after 9th

count=1
while [ $count -le 10 ]
do
	echo "Best School"
	if [ $count = 9 ]
	then
	    echo "Hi"
	fi
	((count++))
done
