#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes:
#	display hours from 0 to 12
#	display minutes from 1 to 59


count=0
while [ $count -le 12 ]
do
    echo "Hour: $count"
    minute=1
    while [ $minute -le 59 ]
    do
	echo "$minute"
	((minute++))
    done
    ((count++))
done
